version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hang529/webframe:1.0
    container_name: webframe
    restart: always
    ports:
      - "5000:5000"
    volumes:
        - webframe-volume:/project/data

volumes:
  webframe-volume:
